package com.stmartin;

import org.junit.Before;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;
import static com.stmartin.BSTSequence.*;

/**
 * Created by shentong on 2017/11/9.
 * Spec:
 * 1. input is a the root of a binary search tree. This binary search tree is generated by traversing an array.
 * 2. output is a list of all the arrays that could generate this binary search tree.
 */
public class BSTSequenceSpec {
    private BinaryTreeNode root;

    @Before
    public void setUp() {
        root = new BinaryTreeNode(5);
        root.leftChild = new BinaryTreeNode(3);
        root.rightChild = new BinaryTreeNode(7);
        root.leftChild.leftChild = new BinaryTreeNode(2);
        root.leftChild.rightChild = new BinaryTreeNode(4);
    }

    @Test
    public void testBSTSequence() {
        List<int[]> sequences = findBSTSequences(root);
        assertEquals(sequences.size(), 8);
    }
}
